### ISSUE TITLE
decision tree tracker

### ISSUE THREAD

**Issue by achen88** [achen88/mp3-metadata-suggester#2]
- [x] remove ampersands
- [x] remove parentheses + brackets
  - [x] keep remix info
    - [ ] standardize remix tag
- [ ] instrumental
- [ ] acapella
- [ ] is "audio" part of the song or artist name?
- [ ] original mix, extended mix
- search w/ and w/o featured artist
  - [x] w/o
  - [ ] w/

**Comment by achen88** [comment]
I've decided a better way is to do a rough match and let the user figure out the rest. Ultimately there's too many edge cases and overfitting is too big a problem with the amount of monkey business that people include in their song titles
