### ISSUE TITLE
heuristic tracker

### ISSUE THREAD

**Issue by achen88** [achen88/mp3-metadata-suggester#5]
- [ ] do not remove featured artist
- [ ] search for remix or no? 
  - can we obtain remixer name w/ high fidelity
- [ ] don't bring up a remix for an original song
- [ ] bring back original mix, extended mix, acapella tags
